

logging:
  level:
#    root: trace #设置root级别
#    com.xiang.log: trace  # 当前项目工程没有这个包，假设的一个
    com.xiang.learn: trace # com.xiang.learn 包下的级别
  config: classpath:log4j2.xml

  # 配置了 logback-spring.xml或者log4j2.xml文件 可以注释掉下面配置
  file:
#    path: E:\my-tool\log # 生成指定目录日志文件 （ linux系统 /data/log ）
#    path: logfile # 生成当前项目根目录日志文件
    name: logfile/my.log
  logback:
    rollingpolicy:
      max-file-size: 500KB  # 默认10MB 日志文件大小切割，超过指定数问自动打包成gz文件
      max-history: 2 # 默认7天 日志的保留时间，超过指定数会自动删除
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %clr(%-5level) %clr(%logger{50}){cyan} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} >>> [%thread] >>> %-5level >>> %logger{50} >>> %msg%n'

spring:
  profiles:
    active: dev
#    active: '@profiles.active@'


# UserBean @ConfigurationProperties 写法
user:
  lastName: Xiang
  age: 18
  list:
    - 1
    - 2
    - 3
  maps:
    key1: value1
    key2: value2








# User1Bean @Value 写法
user1:
  lastName: Xiang
  age: 18
  list: 1,2,3
  maps: '{"key1":"value1","key2":"value2"}'